version: 0.2

phases:
  install:
    commands:
      - git submodule update --init --recursive
      - git clone https://github.com/Kode/nodejs_bin.git
      - ~/Library/Android/sdk/tools/bin/sdkmanager --licenses
  build:
    commands:
      - echo Build started on `date`
      - nodejs_bin/node-linux64 make.js android --kore . --from Tests/Empty --noshaders --compile
  post_build:
    commands:
      - echo Build completed on `date`
